name: Build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]
    
jobs:
  build-win32:
    name: Win32 (Windows, VS2022)
    runs-on: windows-latest
    env:
      CFLAGS: /WX
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          
      - name: Configure project
        run: cmake -S . -B build -G "Visual Studio 17 2022"
        
      - name: Build project
        run: cmake --build build --parallel
